"""Property-based API contract testing (Schemathesis, MIT-licensed OSS).

Schemathesis reads MAGIK's own OpenAPI schema (`{BASE_URL}/openapi.json`,
generated by FastAPI from app/main.py + app/api/api_routes.py + app/auth/) and
generates fuzzed requests for every declared operation, asserting the server
never 500s on malformed-but-schema-valid input.

Scope is deliberately GET-only. MAGIK's mutating endpoints (/rag/query,
/ingest, /auth/register, /auth/login, ...) are expensive (LLM inference),
stateful (create real DB rows), and rate-limited (RATE_LIMIT_RPM=60/min,
AUTH_LOGIN_RATE_LIMIT_PER_MIN=5, a guardrail 5-min ban after 5 blocked events/
60s — see app/guardrails/rate_limiter.py). Property-based fuzzing intentionally
sends garbage at high volume, which is exactly what those limits exist to
catch — running it unauthenticated against POST/PUT/DELETE would either
immediately self-lock via the rate limiter (useless test, false "passing")
or, if it didn't, spam real side effects. Authenticated, stateful, concurrent
testing against dedicated test-tenant accounts is k6's job (see perf/k6/), not
Schemathesis's — this file's job is narrower: prove the read-only surface
never crashes on malformed input, per the OpenAPI contract MAGIK itself
publishes.

Reports: `--junitxml` / `--html` wiring lives in the quality.yml /
quality-live.yml CI jobs, not here — this file just defines the test.
"""

from __future__ import annotations

from tests.api_contract.conftest import BASE_URL, SERVER_UP

import pytest

if SERVER_UP:
    import schemathesis
    from hypothesis import HealthCheck, settings

    schema = schemathesis.from_uri(f"{BASE_URL}/openapi.json").include(method="GET")

    # max_examples kept modest: this exercises N GET operations x 5 examples
    # each against a real (possibly GPU-warming) server, not a pure-function
    # fuzz target. deadline=None because retrieval/infra-health endpoints can
    # legitimately take longer than Hypothesis's default 200ms deadline under
    # real (non-mocked) Qdrant/Redis/Mongo load — that's a latency question
    # for k6/perf, not a contract-violation question for Schemathesis.
    @schema.parametrize()
    @settings(max_examples=5, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_api_contract_get_operations(case: "schemathesis.Case") -> None:
        # not_a_server_error is the one check that matters here: malformed
        # query/path params must produce a clean 4xx (or a 401 on protected
        # routes, since fuzzed requests carry no auth token), never a 500.
        case.call_and_validate(checks=(schemathesis.checks.not_a_server_error,))

else:

    def test_api_contract_skipped() -> None:
        pytest.skip(
            f"MAGIK API not reachable at {BASE_URL}/health — start it first "
            f"(`docker compose up -d api qdrant redis mongo` for local mode)."
        )
